import * as cheerio from "cheerio";
import dns from "node:dns/promises";
import net from "node:net";
const USER_AGENT="Smart1SitesPreview/2.0 (+https://smart1sites.com)", MAX_HTML_BYTES=2500000, MAX_PAGES=7, FETCH_TIMEOUT_MS=12000;
const withoutWww=h=>String(h||"").toLowerCase().replace(/^www\./,"");
function isPrivateIp(ip){
  if(!ip)return true;
  if(net.isIPv4(ip)){const p=ip.split(".").map(Number); if([10,127,0].includes(p[0]))return true; if(p[0]===169&&p[1]===254)return true; if(p[0]===192&&p[1]===168)return true; if(p[0]===172&&p[1]>=16&&p[1]<=31)return true; if(p[0]===100&&p[1]>=64&&p[1]<=127)return true; if(p[0]>=224)return true; return false;}
  const v=ip.toLowerCase(); return v==="::1"||v==="::"||v.startsWith("fe80:")||v.startsWith("fc")||v.startsWith("fd");
}
export function normalizeWebsiteUrl(value){let raw=String(value||"").trim(); if(!raw)throw new Error("Enter your current website address."); if(!/^https?:\/\//i.test(raw))raw=`https://${raw}`; const u=new URL(raw); if(!["http:","https:"].includes(u.protocol))throw new Error("Website must use http or https."); u.hash=""; return u;}
async function assertPublicHost(url){if(!url.hostname||url.hostname==="localhost")throw new Error("That website address cannot be scanned."); let addresses; try{addresses=await dns.lookup(url.hostname,{all:true});}catch{throw new Error("We couldn't find that website. Check the address and try again.");} if(!addresses.length||addresses.some(x=>isPrivateIp(x.address)))throw new Error("That website address cannot be scanned.");}
async function readLimited(response){if(!response.body)return""; const r=response.body.getReader(), d=new TextDecoder(); let size=0,text=""; while(true){const {done,value}=await r.read(); if(done)break; size+=value.byteLength; if(size>MAX_HTML_BYTES){try{await r.cancel()}catch{} break;} text+=d.decode(value,{stream:true});} return text+d.decode();}
async function fetchHtml(startUrl){let current=new URL(startUrl); for(let redirects=0;redirects<5;redirects++){await assertPublicHost(current); const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),FETCH_TIMEOUT_MS); let response; try{response=await fetch(current,{redirect:"manual",signal:controller.signal,headers:{"user-agent":USER_AGENT,"accept":"text/html,application/xhtml+xml"}});}finally{clearTimeout(timer)}
    if([301,302,303,307,308].includes(response.status)){const location=response.headers.get("location"); if(!location)throw new Error("The website redirected incorrectly."); current=new URL(location,current); continue;}
    if(!response.ok)throw new Error(`The website returned ${response.status}.`); const type=response.headers.get("content-type")||""; if(!type.includes("text/html")&&!type.includes("application/xhtml+xml"))throw new Error("That address does not appear to be a website page."); return {html:await readLimited(response),finalUrl:current.href};
  } throw new Error("The website redirected too many times.");}
const cleanText=v=>String(v||"").replace(/\s+/g," ").trim();
function resolveUrl(value,base){if(!value||/^data:|^javascript:/i.test(value))return""; try{const u=new URL(value,base); if(!["http:","https:"].includes(u.protocol))return""; u.hash=""; return u.href;}catch{return""}}
const firstSrcFromSet=s=>String(s||"").split(",")[0]?.trim().split(/\s+/)[0]||"";
function uniqueBy(items,keyFn){const seen=new Set(); return items.filter(i=>{const k=keyFn(i); if(!k||seen.has(k))return false; seen.add(k); return true;});}
function likelyUsefulLink(text,url){const hay=`${text} ${url.pathname}`.toLowerCase(); return /(about|service|amenit|menu|reservation|book|contact|review|testimonial|faq|location|direction|product|event|activit|gallery|photo|team|attorney|practice|inventory|catering|camp|site|room|tour)/.test(hay)}
function parsePage(pageUrl,html){const $=cheerio.load(html); $("script,style,noscript,template,svg").remove(); const title=cleanText($("title").first().text()),metaDescription=cleanText($('meta[name="description"]').attr("content")||""),siteName=cleanText($('meta[property="og:site_name"]').attr("content")||""),themeColor=cleanText($('meta[name="theme-color"]').attr("content")||"");
  const logoCandidates=[]; $("img").each((_,el)=>{const n=$(el),alt=cleanText(n.attr("alt")||""),cls=`${n.attr("class")||""} ${n.attr("id")||""}`; if(/logo|brand/i.test(`${alt} ${cls}`)){const src=n.attr("data-lazy-src")||n.attr("data-src")||n.attr("src")||firstSrcFromSet(n.attr("srcset")); const u=resolveUrl(src,pageUrl); if(u)logoCandidates.push(u);}});
  const images=[],ogImage=resolveUrl($('meta[property="og:image"]').attr("content"),pageUrl); if(ogImage)images.push({url:ogImage,alt:"Featured image",score:120});
  $("img").each((_,el)=>{const n=$(el),src=n.attr("data-lazy-src")||n.attr("data-src")||n.attr("data-original")||n.attr("src")||firstSrcFromSet(n.attr("srcset")),url=resolveUrl(src,pageUrl); if(!url)return; const alt=cleanText(n.attr("alt")||""),cls=`${n.attr("class")||""} ${n.attr("id")||""}`.toLowerCase(),width=Number(n.attr("width")||0),height=Number(n.attr("height")||0); let score=0; if(/hero|banner|cover|featured|header/.test(cls))score+=60; if(/logo|icon|avatar|emoji/.test(cls+" "+alt.toLowerCase()))score-=70; if(width>=600||height>=400)score+=30; if(alt.length>3)score+=8; images.push({url,alt,score});});
  const headings=[]; $("h1,h2,h3").each((_,el)=>{const t=cleanText($(el).text()); if(t.length>=3&&t.length<=180)headings.push(t)}); const paragraphs=[]; $("p,li").each((_,el)=>{const t=cleanText($(el).text()); if(t.length>=35&&t.length<=700)paragraphs.push(t)});
  const links=[]; $("a[href]").each((_,el)=>{const hrefRaw=$(el).attr("href")||"",text=cleanText($(el).text()||$(el).attr("aria-label")||""); if(/^tel:/i.test(hrefRaw)){links.push({text,url:hrefRaw});return} if(/^mailto:/i.test(hrefRaw)){links.push({text,url:hrefRaw});return} const href=resolveUrl(hrefRaw,pageUrl); if(href)links.push({text,url:href});});
  const ctas=links.filter(l=>/(reserve|book|schedule|appointment|quote|contact|call|order|shop|buy|apply|start|get started|plan your stay|learn more)/i.test(l.text)); const phones=links.filter(l=>l.url.startsWith("tel:")).map(l=>l.url.replace(/^tel:/,"")),emails=links.filter(l=>l.url.startsWith("mailto:")).map(l=>l.url.replace(/^mailto:/,"").split("?")[0]);
  return {url:pageUrl,title,metaDescription,siteName,themeColor,logo:logoCandidates[0]||"",headings:[...new Set(headings)].slice(0,30),paragraphs:[...new Set(paragraphs)].slice(0,45),links:uniqueBy(links,x=>x.url).slice(0,100),ctas:uniqueBy(ctas,x=>`${x.text}|${x.url}`).slice(0,18),phones:[...new Set(phones)],emails:[...new Set(emails)],images:uniqueBy(images,x=>x.url).sort((a,b)=>b.score-a.score).slice(0,24)};
}
export async function crawlWebsite(inputUrl){const start=normalizeWebsiteUrl(inputUrl),homeFetch=await fetchHtml(start),homeUrl=new URL(homeFetch.finalUrl),siteRoot=withoutWww(homeUrl.hostname),home=parsePage(homeFetch.finalUrl,homeFetch.html),pages=[home],seen=new Set([home.url]);
  const candidates=home.links.filter(l=>/^https?:/i.test(l.url)).map(l=>({...l,parsed:new URL(l.url)})).filter(l=>withoutWww(l.parsed.hostname)===siteRoot&&likelyUsefulLink(l.text,l.parsed)&&!/\.(pdf|jpg|jpeg|png|gif|webp|svg|zip|mp4|mp3)$/i.test(l.parsed.pathname));
  for(const c of candidates){if(pages.length>=MAX_PAGES)break; if(seen.has(c.parsed.href))continue; seen.add(c.parsed.href); try{const f=await fetchHtml(c.parsed.href); pages.push(parsePage(f.finalUrl,f.html));}catch{}}
  const images=uniqueBy(pages.flatMap((p,pageIndex)=>p.images.map(img=>({...img,pageIndex}))),x=>x.url).sort((a,b)=>(b.score+(b.pageIndex===0?20:0))-(a.score+(a.pageIndex===0?20:0))),links=uniqueBy(pages.flatMap(p=>p.links),x=>x.url),ctas=uniqueBy(pages.flatMap(p=>p.ctas),x=>`${x.text}|${x.url}`),headings=[...new Set(pages.flatMap(p=>p.headings))],paragraphs=[...new Set(pages.flatMap(p=>p.paragraphs))];
  return {requestedUrl:inputUrl,finalUrl:home.url,domain:homeUrl.hostname,title:home.title,siteName:home.siteName,metaDescription:home.metaDescription,themeColor:home.themeColor,logo:home.logo,pages:pages.map(p=>({url:p.url,title:p.title,headings:p.headings.slice(0,12),paragraphs:p.paragraphs.slice(0,18)})),headings:headings.slice(0,60),paragraphs:paragraphs.slice(0,90),images:images.slice(0,32),links:links.slice(0,140),ctas:ctas.slice(0,30),phones:[...new Set(pages.flatMap(p=>p.phones))],emails:[...new Set(pages.flatMap(p=>p.emails))],combinedText:pages.map(p=>[p.title,p.metaDescription,p.headings.join("\n"),p.paragraphs.join("\n")].filter(Boolean).join("\n")).join("\n\n--- PAGE ---\n\n").slice(0,75000)};
}
